[storage]
driver = "overlay"
runroot = "/home/runner/.local/share/containers/runroot"
graphroot = "/home/runner/.local/share/containers/storage"

[storage.options]
mount_program = "/usr/bin/fuse-overlayfs"
