name: Update Workbench Manifest
description: |
  Writes a tag value into a JSON manifest file, preserving the shared schema.
inputs:
  path:
    description: Path to the manifest JSON file to update.
    required: true
  tag:
    description: Tag value to write into the manifest.
    required: true
  key:
    description: JSON key to update with the provided tag.
    required: false
    default: tag
  commit-message:
    description: Commit message to use when recording the manifest update (push events only).
    required: false
runs:
  using: composite
  steps:
    - name: Sync workspace
      if: ${{ github.event_name == 'push' && inputs.commit-message != '' }}
      shell: bash
      run: git pull --rebase
    - name: Update the manifest file
      shell: bash
      run: |
        if [[ -z "${{ inputs.tag }}" ]]; then
          echo "tag input must be non-empty" >&2
          exit 1
        fi
        if [[ ! -f "${{ inputs.path }}" ]]; then
          echo "manifest not found: ${{ inputs.path }}" >&2
          exit 1
        fi
        tmp=$(mktemp)
        jq --arg key "${{ inputs.key }}" --arg tag "${{ inputs.tag }}" '.[$key] = $tag' "${{ inputs.path }}" > "$tmp"
        mv "$tmp" "${{ inputs.path }}"
    - name: Commit manifest update
      if: ${{ github.event_name == 'push' && inputs.commit-message != '' }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ inputs.commit-message }}
        file_pattern: ${{ inputs.path }}
        disable_globbing: true
