# my custom bash config

if [[ -f /etc/bash.bashrc ]]; then
  . /etc/bash.bashrc
elif [[ -f /etc/bashrc ]]; then
  . /etc/bashrc
fi

# Source from custom config dir
if [[ -d $HOME/bash.d ]];then
  source $HOME/bash.d/*
fi

export TERM=xterm
export EDITOR=vim

shopt -s cdspell 
shopt -s cdable_vars 
shopt -s checkhash 
shopt -s checkwinsize 
shopt -s mailwarn 
shopt -s sourcepath 
shopt -s no_empty_cmd_completion  
shopt -s cmdhist 
shopt -s histappend histreedit histverify 
shopt -s extglob 
shopt -u mailwarn 
unset MAILCHECK 
 

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options

HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# enable color support of ls and also add handy aliases

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
# Directory navigation aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias mkdir='mkdir -p'
alias du='du -kh'    
alias df='df -kTh'
alias ll='ls -l'
alias la='ls -Ah'
alias l='ls -CF'
alias lal='ls -alh'
alias ls='ls --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Functions 
extract () {
     if [ -f $1 ] ; then
         case $1 in
      *.tar.bz2)   tar xjf $1 ;;
      *.tar.gz)    tar xzf $1 ;;
      *.bz2)       bunzip2 $1 ;;
      *.rar)       rar x $1   ;;
      *.gz)        gunzip $1  ;;
      *.tar)       tar xf $1  ;;
      *.tbz2)      tar xjf $1 ;;
      *.tgz)       tar xzf $1 ;;
      *)           echo "'$1' cannot be extracted via extract()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# copy and go to dir
cpg (){
  if [ -d "$2" ]; then
    cp $1 $2 && cd $2
  else
    cp $1 $2
  fi
}

# move and go to dir
mvg ()  {
  if [ -d "$2" ]; then
    mv $1 $2 && cd $2
  else
    mv $1 $2
  fi
}

function swap()  {
  local TMPFILE=tmp.$$ 
  mv "$1" $TMPFILE 
  mv "$2" "$1" 
  mv $TMPFILE "$2" 
 }

function sshg() {
if [[ -n $ssh_key_path ]] ; then
    eval $(keychain --quiet --eval $ssh_key_path/$1)
else
    eval $(keychain --quiet --eval $1)
fi
}


