name: Read Current Image Tag
description: |
  Reads a JSON manifest file and exposes the selected tag value.
inputs:
  path:
    description: Path to the manifest JSON file.
    required: false
    default: versions/universal-workbench.json
  key:
    description: JSON key to read from the manifest file.
    required: false
    default: tag
outputs:
  tag:
    description: 'The tag value extracted from the manifest.'
    value: ${{ steps.read.outputs.tag }}
runs:
  using: 'composite'
  steps:
    - name: Read the tag
      id: read
      shell: bash
      run: |
        if [[ ! -f "${{ inputs.path }}" ]]; then
          echo "manifest not found: ${{ inputs.path }}" >&2
          exit 1
        fi
        value=$(jq -r --arg key "${{ inputs.key }}" '.[$key]' "${{ inputs.path }}")
        if [[ -z "$value" || "$value" == "null" ]]; then
          echo "key '${{ inputs.key }}' missing in ${{ inputs.path }}" >&2
          exit 1
        fi
        echo "tag=$value" >> "$GITHUB_OUTPUT"
