version: '3.9'

services:
  pulumi-workbench:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PULUMI_TAG: 3.199.0
        PULUMICTL_VERSION: 0.0.46
        DELVE_VERSION: 1.24.2
        GOLANGCI_LINT_VERSION: 2.1.6
        KUBECTL_VERSION: 1.34.0
        NODE_VERSION: 22
      additional_contexts:
        shared: ../shared
    image: pulumi-workbench:test
    entrypoint: ["/bin/bash", "-lc"]
    command: ["sleep infinity"]
    tty: true
    stdin_open: true
