version: '3.9'

services:
  pulumi-workbench:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PULUMI_VERSION: 3.200.0
        PULUMICTL_VERSION: 0.0.46
        KUBECTL_VERSION: 1.34.0
        UNIVERSAL_WORKBENCH_TAG: sha-dev
        PULUMI_MCP_VERSION: 0.2.0
      additional_contexts:
        shared: ../shared
    image: pulumi-workbench:test
    entrypoint: ["/bin/bash", "-lc"]
    command: ["sleep infinity"]
    tty: true
    stdin_open: true
