name: Build and Publish Anki Desktop Docker image

on:
  push:
    paths:
      - 'anki-desktop-docker/**'
      - '.github/workflows/anki-docker-publish.yaml'
  workflow_dispatch:


jobs:
  build:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        anki_version: [25.02.5]
    uses: spigell/my-shared-workflows/.github/workflows/docker-build-release.yaml@main
    secrets: inherit
    with:
      image-name: anki-desktop-docker
      context: ./anki-desktop-docker
      version: ${{ matrix.anki_version }}
      build-args: |
        ANKI_VERSION=${{ matrix.anki_version }}
