name: Build and Publish Anki Desktop Docker image

on:
  push:
    paths:
      - 'anki-desktop-docker/**'
      - '.github/workflows/anki-docker-publish.yaml'
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        anki_version: [25.02.5]
    uses: spigell/my-shared-workflows/.github/workflows/docker-build.yaml@main
    secrets: inherit
    with:
      image-name: anki-desktop-docker
      context: ./anki-desktop-docker
      dockerfile: ./anki-desktop-docker/Dockerfile
      version: ${{ matrix.anki_version }}
      build-args: |
        ANKI_VERSION=${{ matrix.anki_version }}
