name: Build and Publish Gemini CLI images

on:
  push:
    paths:
      - 'gemini-cli/**'
      - 'gemini-cli-workbench/**'
      - '.github/workflows/gemini-cli-publish.yaml'
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  build-gemini-cli:
    uses: spigell/my-shared-workflows/.github/workflows/docker-build-release.yaml@main
    secrets: inherit
    with:
      image-name: gemini-cli
      context: ./gemini-cli
      version: 0.8.1
      build-args: |
        GEMINI_CLI_VERSION=0.8.1

  build-gemini-cli-workbench:
    needs: build-gemini-cli
    uses: spigell/my-shared-workflows/.github/workflows/docker-build-release.yaml@main
    secrets: inherit
    with:
      image-name: gemini-cli-workbench
      context: ./gemini-cli-workbench
      version: ${{ needs.build-gemini-cli.outputs.version }}
      build-args: |
        GEMINI_CLI_TAG=${{ needs.build-gemini-cli.outputs.sha-tag }}
